
//Assets
export const FETCH_ASSETS_SUCCESS='FETCH_ASSETS_SUCCESS';

export const FETCH_ASSETS_ERROR='FETCH_ASSETS_ERROR';

export const FETCH_ASSETS_REQUEST='FETCH_ASSETS_REQUEST';

//Images

export const FETCH_IMG_SUCCESS='FETCH_IMG_SUCCESS';

export const FETCH_IMG_ERROR='FETCH_IMG_ERROR';

export const FETCH_IMG_REQUEST='FETCH_IMG_REQUEST';

